export const data = [
  {
    age: 0,
    case_id: 1,
    city: "",
    color: "#00cc66",
    confirmed_on: "30 Jan 2020",
    discharged_on: "05 Feb 2020",
    hospitalized_on: "31 Jan 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "Wuhan, China"
  },
  {
    age: 0,
    case_id: 2,
    city: "",
    color: "#00cc66",
    confirmed_on: "01 Feb 2020",
    discharged_on: "05 Feb 2020",
    hospitalized_on: "01 Feb 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "Wuhan, China"
  },
  {
    age: 0,
    case_id: 3,
    city: "",
    color: "#00cc66",
    confirmed_on: "02 Feb 2020",
    discharged_on: "07 Feb 2020",
    hospitalized_on: "02 Feb 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "Wuhan, China"
  },
  {
    age: 0,
    case_id: 4,
    city: "",
    color: "#00cc66",
    confirmed_on: "02 Mar 2020",
    discharged_on: "",
    hospitalized_on: "02 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 5,
    city: "",
    color: "#00cc66",
    confirmed_on: "02 Mar 2020",
    discharged_on: "",
    hospitalized_on: "02 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 6,
    city: "",
    color: "#00cc66",
    confirmed_on: "03 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Telangana",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "Dubai, UAE"
  },
  {
    age: 0,
    case_id: 7,
    city: "Jaipur",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "11 Mar 2020",
    hospitalized_on: "04 Mar 2020",
    icu_on: "05 Mar 2020",
    name: "",
    nationality: "Indian",
    state: "Rajasthan",
    status: "RECOVERED",
    transmission_type: "Local",
    travel_city_country: "India"
  },
  {
    age: 0,
    case_id: 8,
    city: "Jaipur",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Rajasthan",
    status: "RECOVERED",
    transmission_type: "Local",
    travel_city_country: "India"
  },
  {
    age: 0,
    case_id: 9,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 10,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 11,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 12,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 13,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 14,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 15,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 16,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 17,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 18,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 19,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 20,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 21,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 22,
    city: "Gurugram",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 23,
    city: "Ghaziabad",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "UAE, Dubai"
  },
  {
    age: 0,
    case_id: 24,
    city: "Ghaziabad",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "RECOVERED",
    transmission_type: "Local",
    travel_city_country: "India"
  },
  {
    age: 0,
    case_id: 25,
    city: "Agra",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "RECOVERED",
    transmission_type: "Local",
    travel_city_country: "India"
  },
  {
    age: 0,
    case_id: 26,
    city: "Agra",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "RECOVERED",
    transmission_type: "Local",
    travel_city_country: "India"
  },
  {
    age: 0,
    case_id: 27,
    city: "Agra",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "15 Mar 2020",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "UAE, Dubai"
  },
  {
    age: 0,
    case_id: 28,
    city: "Agra",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 29,
    city: "Agra",
    color: "#00cc66",
    confirmed_on: "04 Mar 2020",
    discharged_on: "",
    hospitalized_on: "04 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: "India"
  },
  {
    age: 0,
    case_id: 30,
    city: "Delhi",
    color: "#00cc66",
    confirmed_on: "05 Mar 2020",
    discharged_on: "",
    hospitalized_on: "05 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 31,
    city: "Delhi",
    color: "#00cc66",
    confirmed_on: "06 Mar 2020",
    discharged_on: "",
    hospitalized_on: "06 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 32,
    city: "Ladakh",
    color: "#00cc66",
    confirmed_on: "07 Mar 2020",
    discharged_on: "",
    hospitalized_on: "07 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Iran"
  },
  {
    age: 0,
    case_id: 33,
    city: "Ladakh",
    color: "#00cc66",
    confirmed_on: "07 Mar 2020",
    discharged_on: "",
    hospitalized_on: "07 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Iran"
  },
  {
    age: 0,
    case_id: 34,
    city: "Chennai",
    color: "#00cc66",
    confirmed_on: "07 Mar 2020",
    discharged_on: "18 Mar 2020",
    hospitalized_on: "07 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Tamil Nadu",
    status: "RECOVERED",
    transmission_type: "Imported",
    travel_city_country: "Oman"
  },
  {
    age: 0,
    case_id: 35,
    city: "Pathnamthitta",
    color: "#00cc66",
    confirmed_on: "08 Mar 2020",
    discharged_on: "",
    hospitalized_on: "08 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Oman"
  },
  {
    age: 0,
    case_id: 36,
    city: "Pathnamthitta",
    color: "#00cc66",
    confirmed_on: "08 Mar 2020",
    discharged_on: "",
    hospitalized_on: "08 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Oman"
  },
  {
    age: 0,
    case_id: 37,
    city: "Pathnamthitta",
    color: "#00cc66",
    confirmed_on: "08 Mar 2020",
    discharged_on: "",
    hospitalized_on: "08 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Oman"
  },
  {
    age: 0,
    case_id: 38,
    city: "Pathnamthitta",
    color: "#00cc66",
    confirmed_on: "08 Mar 2020",
    discharged_on: "",
    hospitalized_on: "08 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Oman"
  },
  {
    age: 0,
    case_id: 39,
    city: "Pathnamthitta",
    color: "#00cc66",
    confirmed_on: "08 Mar 2020",
    discharged_on: "",
    hospitalized_on: "08 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Oman"
  },
  {
    age: 63,
    case_id: 40,
    city: "",
    color: "#00cc66",
    confirmed_on: "09 Mar 2020",
    discharged_on: "",
    gender: "female",
    hospitalized_on: "09 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "J&K",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Iran"
  },
  {
    age: 3,
    case_id: 41,
    city: "",
    color: "#00cc66",
    confirmed_on: "09 Mar 2020",
    discharged_on: "",
    gender: "male",
    hospitalized_on: "09 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "J&K",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Iran"
  },
  {
    age: 0,
    case_id: 42,
    city: "",
    color: "#00cc66",
    confirmed_on: "09 Mar 2020",
    discharged_on: "",
    hospitalized_on: "09 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Oman"
  },
  {
    age: 0,
    case_id: 43,
    city: "",
    color: "#00cc66",
    confirmed_on: "09 Mar 2020",
    discharged_on: "",
    hospitalized_on: "09 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Iran"
  },
  {
    age: 76,
    case_id: 44,
    city: "Bengaluru",
    color: "#00cc66",
    confirmed_on: "09 Mar 2020",
    discharged_on: "",
    hospitalized_on: "09 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "DIED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 45,
    city: "Amritsar",
    color: "#00cc66",
    confirmed_on: "09 Mar 2020",
    discharged_on: "",
    hospitalized_on: "09 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Punjab",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 46,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "10 Mar 2020",
    discharged_on: "",
    hospitalized_on: "10 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Dubai, UAE"
  },
  {
    age: 0,
    case_id: 47,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "10 Mar 2020",
    discharged_on: "",
    hospitalized_on: "10 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Dubai, UAE"
  },
  {
    age: 0,
    case_id: 48,
    city: "Bengaluru",
    color: "#00cc66",
    confirmed_on: "10 Mar 2020",
    discharged_on: "",
    hospitalized_on: "10 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "USA"
  },
  {
    age: 0,
    case_id: 49,
    city: "Bengaluru",
    color: "#00cc66",
    confirmed_on: "10 Mar 2020",
    discharged_on: "",
    hospitalized_on: "10 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "USA"
  },
  {
    age: 0,
    case_id: 50,
    city: "Bengaluru",
    color: "#00cc66",
    confirmed_on: "10 Mar 2020",
    discharged_on: "",
    hospitalized_on: "10 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "USA"
  },
  {
    age: 0,
    case_id: 51,
    city: "Delhi",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 85,
    case_id: 52,
    city: "Jaipur",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Rajasthan",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Dubai, UAE"
  },
  {
    age: 0,
    case_id: 53,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 54,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 55,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 56,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 57,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 58,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 59,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 60,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 45,
    case_id: 61,
    city: "Nagpur",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 62,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 63,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 64,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 65,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 66,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 67,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 68,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 69,
    city: "Delhi",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    died_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "DIED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 70,
    city: "",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Rajasthan",
    status: "RECOVERED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 71,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "11 Mar 2020",
    discharged_on: "",
    hospitalized_on: "11 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 72,
    city: "Ladakh",
    color: "#00cc66",
    confirmed_on: "12 Mar 2020",
    discharged_on: "",
    hospitalized_on: "12 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 73,
    city: "",
    color: "#00cc66",
    confirmed_on: "12 Mar 2020",
    discharged_on: "",
    hospitalized_on: "12 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 74,
    city: "",
    color: "#00cc66",
    confirmed_on: "12 Mar 2020",
    discharged_on: "",
    hospitalized_on: "12 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 75,
    city: "",
    color: "#00cc66",
    confirmed_on: "12 Mar 2020",
    discharged_on: "",
    hospitalized_on: "12 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Andhra Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    case_id: 76,
    city: "Bengaluru",
    confirmed_on: "12 Mar 2020",
    discharged_on: "",
    hospitalized_on: "12 Mar 2020",
    icu_on: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Local"
  },
  {
    age: 0,
    case_id: 77,
    city: "",
    color: "#00cc66",
    confirmed_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "13 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 78,
    city: "",
    color: "#00cc66",
    confirmed_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "13 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 79,
    city: "",
    color: "#00cc66",
    confirmed_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "13 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 80,
    city: "",
    color: "#00cc66",
    confirmed_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "13 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 81,
    city: "",
    color: "#00cc66",
    confirmed_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "13 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 82,
    city: "Bengaluru",
    color: "#00cc66",
    confirmed_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "13 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 83,
    city: "Delhi",
    color: "#00cc66",
    confirmed_on: "13 Mar 2020",
    discharged_on: "",
    hospitalized_on: "13 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: "India"
  },
  {
    age: 0,
    case_id: 84,
    city: "",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 85,
    city: "Yavatmal",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Dubai, UAE"
  },
  {
    age: 0,
    case_id: 86,
    city: "Yavatmal",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Dubai, UAE"
  },
  {
    age: 0,
    case_id: 87,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 88,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 89,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 64,
    case_id: 90,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "DIED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 91,
    city: "",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 92,
    city: "",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 93,
    city: "",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 24,
    case_id: 94,
    city: "",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Telangana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Spain"
  },
  {
    age: 0,
    case_id: 95,
    city: "Hyderabad",
    color: "#00cc66",
    confirmed_on: "14 Mar 2020",
    discharged_on: "",
    hospitalized_on: "14 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Telangana",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 96,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 97,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 98,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 99,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 100,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 101,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 102,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 103,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 104,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 105,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 59,
    case_id: 107,
    city: "Mumbai",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    gender: "male",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 108,
    city: "",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttarakhand",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 109,
    city: "",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 59,
    case_id: 110,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "15 Mar 2020",
    discharged_on: "",
    gender: "female",
    hospitalized_on: "15 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 111,
    city: "Bhubaneswar",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Odisha",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: "Italy"
  },
  {
    age: 0,
    case_id: 112,
    city: "",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 113,
    city: "",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 114,
    city: "",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "J&K",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 115,
    city: "",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 115,
    city: "",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 116,
    city: "Navi Mumbai",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 117,
    city: "Navi Mumbai",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 118,
    city: "Kalyan",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 119,
    city: "Kalyan",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 120,
    city: "Navi Mumbai",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 121,
    city: "Navi Mumbai",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 122,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Telangana",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 123,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 124,
    city: "",
    color: "#00cc66",
    confirmed_on: "16 Mar 2020",
    discharged_on: "",
    hospitalized_on: "16 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 125,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 126,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 127,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 128,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 129,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 130,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 131,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 132,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 133,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 134,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 135,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Telangana",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 136,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 137,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 138,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 18,
    case_id: 139,
    city: "",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "17 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "West Bengal",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "United Kingdom"
  },
  {
    age: 0,
    case_id: 140,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Foreign",
    state: "Delhi",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 141,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Delhi",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 142,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Haryana",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 143,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Kerala",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 144,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 145,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Uttar Pradesh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 146,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 0,
    case_id: 147,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Ladakh",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 68,
    case_id: 148,
    city: "Mahe",
    color: "#00cc66",
    confirmed_on: "17 Mar 2020",
    discharged_on: "",
    hospitalized_on: "10 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Puducherry",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "UAE"
  },
  {
    age: 20,
    case_id: 149,
    city: "Pune",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "France,Netherlands"
  },
  {
    age: 56,
    case_id: 150,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "USA"
  },
  {
    age: 25,
    case_id: 151,
    city: "",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Karnataka",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Spain"
  },
  {
    age: 0,
    case_id: 152,
    city: "Chennai",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Tamil Nadu",
    status: "HOSPITALIZED",
    transmission_type: "Local",
    travel_city_country: ""
  },
  {
    age: 50,
    case_id: 153,
    city: "Ratnagiri",
    color: "#00cc66",
    confirmed_on: "18 Mar 2020",
    discharged_on: "",
    gender: "male",
    hospitalized_on: "18 Mar 2020",
    icu_on: "",
    name: "",
    nationality: "Indian",
    state: "Maharashtra",
    status: "HOSPITALIZED",
    transmission_type: "Imported",
    travel_city_country: "Dubai"
  }
];
